---
title: "fifty-states"
description: |
  Demo page for fifty-states project. Not linked from main site.
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(tigris)
library(tidyverse)
library(ggiraph)

usa <- states(year = 2020) %>%
    filter(STUSPS %in% state.abb) %>%
    shift_geometry()

temppath <- fs::file_temp(ext = 'xlsx')
download.file(url = 'https://www2.census.gov/programs-surveys/decennial/2020/data/apportionment/apportionment-2020-table01.xlsx', destfile = temppath)

appor <- readxl::read_xlsx(temppath,
                  skip = 4, col_names = c('NAME', 'pop', 'nrep', 'delta'))

usa <- usa %>% left_join(appor, by = 'NAME')

usa <- usa %>% mutate(link = 'https://alarm-redist.github.io/')

p <- usa %>%
    ggplot(aes(fill = as.character(delta))) +
    geom_sf_interactive(aes(onclick = paste0('window.open("', link , '")'))) +
    theme_void() +
  guides(fill = 'none')


```

# Demo

All links set to the same thing, colored for demo with no legend.


```{r, echo = FALSE}
girafe(ggobj = p, 
       options = list(opts_hover(css = "fill:#CC7810;stroke:black;cursor:pointer;opacity:0.80",
               reactive = TRUE)))
```





